### ISSUE TITLE
H and V commands that come right after M cause NaN values.

### ISSUE THREAD

**Issue by achrist** [lukem512/normalize-svg-path#10]
When trying to normalize a path with the following definition the NaN values are returned.

`d="M 175 200 V 300"`

The resulting normalized coordinates end up being:

`MNaN 0.00000000000000000v-1.00000000000000000`

I believe this is due to the formula in the `scale` method as seen here...

`((scalar * (x - oldMin)) / (oldMax - oldMin)) + newMin`

In this scenario the `oldMax` and `oldMin` as well as the `x` value are all equal. This results in an expression of `0/0` which evaluates to `NaN`. This happens for both `V` and `H` and the `NaN` value shows up for the opposite property than the command provides. So `H` gets `NaN` for the `y` coordinate and `V` gets `NaN` for the `x` coordinate for the `M` command in the definition.

**Comment by lukem512** [comment]
Thanks for reporting this issue. I've been AFK for the last year but will investigate and push a fix.

**Comment by lukem512** [comment]
I believe this is closed in 5cec50a
