### ISSUE TITLE
Arc tests

### ISSUE THREAD

**Issue by dy** [lukem512/normalize-svg-path#5]
Since arc command has `A rx ry x-axis-rotation large-arc-flag sweep-flag x y` signature, the even/odd x/y coordinate guess won't work.

As a workaround - using [normalize-svg-path](https://github.com/jkroso/normalize-svg-path) command before normalizing svg coords, but it handles arcs wrong https://github.com/jkroso/normalize-svg-path/issues/2.

**Comment by lukem512** [comment]
Fixed with f6b6118988ba04241203b86b3aa824b8af34d2f9

**Comment by dy** [comment]
Awesome, thanks @lukem512!
