### ISSUE TITLE
Detect viewBox automatically

### ISSUE THREAD

**Issue by dy** [lukem512/normalize-svg-path#6]
Hi @lukem512!

Recently finished [svg-path-bounds](https://github.com/dfcreative/svg-path-bounds) for detecting bounding box of an svg-path.

Is there any sense to integrate it, or you would rather prefer the current state of `viewBox` affairs?

**Comment by lukem512** [comment]
Hey! This is cool, thanks for taking the time to create it. It makes sense to me to use this when a `viewBox` is omitted from the args.

One thing is that you mention `normalize-svg-coords` (in `Related`) as normalizing between `0..1`; with v1.0.2 it is now possible to normalize between any linear range. Are you able to update that, please?

**Comment by dy** [comment]
@lukem512 done

**Comment by lukem512** [comment]
Fixed in 21b604bad55a0384391b4b0911788b69a089519e
