### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by dy** [lukem512/normalize-svg-path#7]
There is a convention in other packages to return segments list instead of a string:

* [abs-svg-path](https://www.npmjs.com/package/abs-svg-path)
* [rel-svg-path](https://www.npmjs.com/package/rel-svg-path)
* [normalize-svg-path](https://www.npmjs.com/package/normalize-svg-path)

Is there any sense to do the same here? Or mb return same format of path as the input, ie. if it is a string, then return normalized string, otherwise return segments? That is pretty useful to have chunks returned in case if additional transformations required.

**Comment by lukem512** [comment]
Fixed in 82867c6c25d01638714423f63f5a20d7e968b091 and tests corrected in f6bc6ed0d090914af90da6477212d9ca72f24e55
