### ISSUE TITLE
understanding normalize

### ISSUE THREAD

**Issue by swampthang** [lukem512/normalize-svg-path#9]
Thanks for the module!

I have a path (just an example because there are a few others of different aspect ratios)
`'M50.2,66.3c20,0,112,0,150,0s168,0,200,0s161,0,200,0s127,0,150,0'` which is just a horizontal bezier path with a couple of controls points.
The viewBox is '0 0 1280 720' but can change dynamically so am wanting some way to normalize the path's width or height depending on whether the path is taller or wider. I tried this...
```
function normalizedBezPath(path) {
  let vb = getViewBox(); // returns '0 0 1280 720' or whatever it happens to be at the time
  let max = Settings.getStageHeight(); // I'm not sure what to use here.
  return normalize({
    viewBox: vb,
    path: path,
    min: 0,
    max: max,
    asList: false
  });
}
```
What I end up with is a path that's resized in height only. 

I don't understand SVG normalize so any help you could give in explaining what the max and min values actually do. If I better understood I might be able to dynamically set the values accordingly.

**Comment by lukem512** [comment]
The module will normalise the coordinate points between the `min` and `max` values you've specified. For example, if you wanted each coordinate to be a decimal value between `0` and `1`, you'd set `min` and `max` to those respective values.

This module is only capable of normalising `x` and `y` uniformly and I think, for your use-case, you'd need to set upper and lower bounds for both axes independently.

If you'd like to make a PR it would be very well received. Much of the codebase is already established it would just need implementing and testing for all relevant instructions.

I'll close this for now but please get in touch if you'd like to collaborate :+1:
